# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RealmQnA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift', '3.0.0-rc.1'
  pod 'RealmLoginKit'
end
